### ISSUE TITLE
/channel - Usage description missing wording

### ISSUE THREAD

**Issue by iAmCLY** [raysun/SidekickIssues#10]
<img width="614" alt="screen shot 2017-07-25 at 12 32 27 am" src="https://user-images.githubusercontent.com/26148953/28560796-d475e1fe-70d0-11e7-8514-2a8b515abbf4.png">

On Usage description it should be:
Usage
/channel #channel #R2P8GR92
Set #channel to Clan #R2P8GR92
/channel #channel #R2P8GR92 [FEED | WAR | REMOVE]
Set Clash FEED or WAR log to #channel. Or REMOVE channel from clan.
If no Clan tag given, uses this channel's clan

**Comment by xDp64xG** [comment]
This is because the bot is looking for these words: clan | channel. It could be possible to have /clan show the bottom half and /channel do what you said

**Comment by iAmCLY** [comment]
Fixed
