### ISSUE TITLE
SK shows deleted channels, and old names for renamed channels

### ISSUE THREAD

**Issue by xDp64xG** [raysun/SidekickIssues#14]
![image](https://user-images.githubusercontent.com/23390936/28604242-30bf4a56-7197-11e7-955e-f7e7d9df0e55.png)

Channels that are X'd out shouldn't be there because it is deleted

**Comment by raysun** [comment]
In addition, if a channel is renamed, we still show the old name.

The fix is relatively simple. Whenever we are displaying a channel name, we should use its .id to retrieve its current name. If it's not there, then it has been deleted.
