### ISSUE TITLE
/upgrade - Wall Breaker not returning 'Wall Breaker

### ISSUE THREAD

**Issue by xDp64xG** [raysun/SidekickIssues#15]
Error Code:

> Thu Jul 27 05:25:40 PM, Executing command: S
Thu Jul 27 05:25:40 PM, msg.cmd found S
Thu Jul 27 05:25:40 PM, searching for /s wall breaker
Thu Jul 27 05:25:40 PM, post-synonym query is Walls BREAKER
Thu Jul 27 05:25:40 PM, search engine doc count is 223
Thu Jul 27 05:25:40 PM, Filtered out 0 result
Thu Jul 27 05:25:40 PM, # of results 0
Thu Jul 27 05:25:40 PM, matched terms set()
Thu Jul 27 05:25:40 PM, matched_terms values only []
Thu Jul 27 05:25:40 PM, clash.search returned None

**Comment by raysun** [comment]
fixed in beta, please test

**Comment by iAmCLY** [comment]
It works in beta
