### ISSUE TITLE
/upgrade - Data need to update

### ISSUE THREAD

**Issue by iAmCLY** [raysun/SidekickIssues#28]
Data from June 2017 Balancing Update

- ~~NEW: P.E.K.K.A. level 6 (TH11)~~
- ~~NEW: Wizard level 8 (TH11)~~
- ~~NEW: Healer level 5 (TH11)~~
- ~~NEW: Miner level 5 (TH11)~~
- ~~Miner level 3 is now available at Town Hall 10 (was at TH11)~~
- ~~NEW: Wall Breaker level 7 (TH11)~~

- Levels 11 – 12 for all Troops after upgrading the Star Laboratory to Level 6
- Levels 6 – 10 for the Battle Machine
- NEW: The Night Witch

**Comment by raysun** [comment]
Where are we with this? Is this still a bug / does spanser have the right info on coc.guide?

**Comment by iAmCLY** [comment]
coc.guide has correct data:
![80d199bf-625d-4ed0-a47d-699e0c91b16c](https://user-images.githubusercontent.com/26148953/29488716-92609ec2-84c5-11e7-9c66-12b7bb174558.png)

Here’s what SK has:
![62fce4c9-ef8d-4cdc-9180-5b70c6bcf164](https://user-images.githubusercontent.com/26148953/29488720-a2f15b96-84c5-11e7-88be-abb5d11461c0.png)

The miner on TH10 suppostly up to Lv3

**Comment by iAmCLY** [comment]
I just check the miner coz I dont know how to check every troops on /upgrade manually. Thats why I posted all the Balancing update data from supercell and crossed out that im sure is correct.

**Comment by raysun** [comment]
Take a look at the files in data/ in the ActualBeta branch. The JSON files, especially characters.json

**Comment by iAmCLY** [comment]
Will do
