### ISSUE TITLE
Open Base - Not showing the best %

### ISSUE THREAD

**Issue by iAmCLY** [raysun/SidekickIssues#33]
The open base % did not update the best %

<img width="427" alt="screen shot 2017-08-23 at 12 34 28 am" src="https://user-images.githubusercontent.com/26148953/29604074-2d53eb6e-879b-11e7-8f84-6e5d53d7bb41.png">

After xexo attack on #1, The % suppostly 79%

**Comment by raysun** [comment]
Fixed in beta.
