### ISSUE TITLE
/members - Simple list of clan members

### ISSUE THREAD

**Issue by iAmCLY** [raysun/SidekickIssues#38]
<img width="401" alt="screen shot 2017-08-28 at 2 09 51 pm" src="https://user-images.githubusercontent.com/26148953/29793897-940b4db2-8bfa-11e7-933f-79b6313986fd.png">
<img width="266" alt="screen shot 2017-08-28 at 2 10 19 pm" src="https://user-images.githubusercontent.com/26148953/29793911-a517b60e-8bfa-11e7-9e70-79de3e8572f8.png">

The member list shows:
TH - Heroes - Maybe length of stay

**Comment by xDp64xG** [comment]
Length of stay would have to be data pulled from, more than likely, Clash of Stats, otherwise the bot would overload trying to save everyones time in a clan, or I think so. Other 2 are easy to keep track of which could be arranged.

**Comment by iAmCLY** [comment]
Yeah, we can pulled data from CoS. Length of stay will be awesome feature for /members

**Comment by IamCLY** [comment]
Added

**Comment by Werewolf75** [comment]
Would love to see /members th9. Or /members @th10 showing a list of th9 or th10 members respectively
