### ISSUE TITLE
Add command to view the status of all wars Sidekick is linked to

### ISSUE THREAD

**Issue by PMITpaul** [raysun/SidekickIssues#39]
Add a command to view the status of all wars in all clans sidekick is linked to on your server.  This would allow you to know the statuses without having to run the command in each channel.  For Example,  /allwars may show something like the following with one line per clan:

alpha and omega vs enemy1 - 30v30 - Starts in 5hr 30min
alpha rising vs enemy2 - 15 v 15 - Starts in 12hr 10min
ameri-KHANS vs enemy3 - 25 v 25 - Ends in 6hr 20 min - winning 52 to 50

**Comment by IamCLY** [comment]
Added
