### ISSUE TITLE
Enhancement of /best = `/best donation`

### ISSUE THREAD

**Issue by unseenmagik** [raysun/SidekickIssues#42]
This is an addition to the current /best command. 

The donation feature of SK is something that our clan really like to use. The current issue with the season reset has brought this to light even more so. Linked too [40](https://github.com/raysun/SidekickIssues/issues/40)

There is a requirement from our clan to stay within the 1:2 donation ratio. If the donations are too low, this means the player is not contributing to the clan. If someones donations are too high, this can cause peoples dontaions to be too low so there is a ballance that the Co's need to keep an eye on. 

<b>/BEST DONATION</b>
This command will show the best donations seperatley from the /best command. 
It should contain more details on the ratio's donated. displaying the donated/received for even better as a ratio. 

<b>/BEST DONATION SEASON</b>
This is a further extension of the above and just like my issue [41](https://github.com/raysun/SidekickIssues/issues/41) where the donations should be looked at for the season and not just based on the week commencing from the Monday. When the season resets, so does SK data tables. An auto post at the end of the season would be even better to show a list of the donations in a ratio and <b>Bold</b> any of the names that are linked to discord that are under or over the 1:2 ratio.

<b>/BEST DONATION SETTINGS <ratiopart1> <ratiopart2></b> 
example `/best donations settings 1 2` = donation settings will be set to donations based on 1:2

This settings option is an advansed feature that would be fantastic but not required if the settings are set too 1:2.

**Comment by iAmCLY** [comment]
Maybe we can implement this together with #38

**Comment by unseenmagik** [comment]
You may be able to use a pull request from the Clash of Stats site. 
An example would be like this:
https://cdn.discordapp.com/attachments/308820731515371523/354251721934897152/unknown.png

**Comment by unseenmagik** [comment]
@raysun here is one for you

**Comment by unseenmagik** [comment]
![2017-09-06 09_42_12- suggestions - discord](https://user-images.githubusercontent.com/30931287/30102473-b06f327c-92e7-11e7-95b8-2766617d5c4e.png)

Example above

**Comment by IamCLY** [comment]
Added

**Comment by iAmCLY** [comment]
merge with #75
