### ISSUE TITLE
Donation data on /best is not match with in game.

### ISSUE THREAD

**Issue by iAmCLY** [raysun/SidekickIssues#49]
<img width="494" alt="screen shot 2017-09-14 at 5 39 32 pm" src="https://user-images.githubusercontent.com/26148953/30461501-c4fb5e5e-9973-11e7-905f-f437265df29d.png">

**Comment by raysun** [comment]
Probably just a delay in SK updating? I now show last update time in /?

**Comment by iAmCLY** [comment]
It looks like the update time in is in wrong place. Is in /help instead /best for now

<img width="604" alt="screen shot 2017-09-20 at 2 09 01 pm" src="https://user-images.githubusercontent.com/26148953/30667729-5bdc4174-9e0d-11e7-83c4-13b2e9240dd9.png">
