### ISSUE TITLE
/upgrade - Add in the new update of troop levels at th11 (Like level 5 healers)

### ISSUE THREAD

**Issue by iAmCLY** [raysun/SidekickIssues#5]
Command: /upgrade

What I mean:
Add in the new update of troop levels at th11 (Like level 5 healers)

**Comment by iAmCLY** [comment]
The Builder Base has inaccuatate daya as well

Sample:
- I have Battle Mechine Lv1 
- SK show BM lv1 instead of 2
- I dont have canon cart
- SK show Canon Cart update lv2

**Comment by xDp64xG** [comment]
The th11 upgrades work, just not BH.
