### ISSUE TITLE
War Log - Implement Color Code Number

### ISSUE THREAD

**Issue by iAmCLY** [raysun/SidekickIssues#53]
With current color code has been implemented to /lineup and Open Base. Maybe we can implement the same color code on war log to make it easier to understand the type of attack.

**Style A**
<img width="408" alt="screen shot 2017-09-20 at 2 17 32 pm" src="https://user-images.githubusercontent.com/26148953/30668072-7b047d18-9e0e-11e7-8eb8-879dd59f0e7f.png">

**Comment by IamCLY** [comment]
Another idea:

<img width="370" alt="screen shot 2017-09-28 at 11 58 12 am" src="https://user-images.githubusercontent.com/26148953/30985196-6cfca506-a444-11e7-86a3-dff3d9e3bcd0.png">

**Comment by iAmCLY** [comment]
**Style B**
<img width="363" alt="screen shot 2017-09-29 at 3 46 26 pm" src="https://user-images.githubusercontent.com/26148953/31038753-634fc31e-a52d-11e7-9b6b-4fdfe88a822f.png">

**Comment by IamCLY** [comment]
Added

**Comment by iAmCLY** [comment]
**Style C**
<img width="420" alt="screen shot 2017-10-16 at 4 00 04 pm" src="https://user-images.githubusercontent.com/26148953/31638956-2c80fa7c-b28b-11e7-953a-ab47b0607cd7.png">
