### ISSUE TITLE
/best - Support for players joining in middle of week

### ISSUE THREAD

**Issue by iAmCLY** [raysun/SidekickIssues#6]
Command: /best

What I mean:
Support best for players joining in middle of week

**Comment by raysun** [comment]
It's an interesting problem, because I only (reliably) have data from the time they joined. I could start calculating from that point, but it'd be more fair to calculate from *before they joined*

**Comment by xDp64xG** [comment]
I agree with raysun. It would be more fair. Imagine joining a game that is either a) that is about to end.

**Comment by iAmCLY** [comment]
So can we close this case?
