### ISSUE TITLE
add remaining attacks at the bottom of /war

### ISSUE THREAD

**Issue by Werewolf75** [raysun/SidekickIssues#64]
purpose :  if we see this total pic in one place, it would be more helpful for the leader / war planner of the clan .

this can be  a separate cmd (for example "status") or an enhancement to the /war cmd.
![image](https://user-images.githubusercontent.com/31430982/31407979-8dbb6662-ae24-11e7-87a1-c46e74ebc4de.png)

**Comment by Werewolf75** [comment]
in the pic open base list is showing number of defenses so that we can send a higher th to clan a base if it has absorbed 3 or more attacks and remaining attacks list is showing the base# a player has attacked in his 1st hit so that he is not allotted for the same base n hero brakeup is there so that we know how has stronger/weaker royals n could be allotted bases accordingly .

**Comment by raysun** [comment]
@IamCLY you built a design mockup for this at one point also, right?

**Comment by iAmCLY** [comment]
Yes, but on old UI.

**Comment by iAmCLY** [comment]
We merge this feature to SK Lineup
