### ISSUE TITLE
Open Bases breakdown on Scoreboard

### ISSUE THREAD

**Issue by iAmCLY** [raysun/SidekickIssues#71]
Add open bases breakdown on scoreboard for better war planning

![d6667092-76f9-46ee-82fe-65200106fb8c](https://user-images.githubusercontent.com/26148953/31954435-6c7a2986-b89a-11e7-8d44-454fc20d5fd7.jpeg)

**Comment by iAmCLY** [comment]
<img width="322" alt="screen shot 2017-10-24 at 4 45 09 pm" src="https://user-images.githubusercontent.com/26148953/31973439-c5849490-b8da-11e7-8952-0eb927348360.png">

**Comment by Werewolf75** [comment]
I vote for this one also.

**Comment by iAmCLY** [comment]
This feature has been implemented on /open
