### ISSUE TITLE
/war - Show lineup + heroes breakdown before the war start

### ISSUE THREAD

**Issue by iAmCLY** [raysun/SidekickIssues#8]
Command: /war

What I mean:
Show Lineup + Heroes Breakdown before the war start

Reason: Some clan has different strategy for the defense (CC) and to elimiate confusion because most of them have write the request on COC itself

Lineup + Heroes Breakdown:

Our lineup on this WAR
War starts in 6 hours and 45 minutes.

TH11 MG 45/45/20
TH11 xexo 45/45/20
TH11 CLY 45/45/20
TH11 zilla 45/45/20
TH10 siloman 40/40/0
TH10 The DanFather 40/36/0
TH10 HybrisJS 26/25/0
TH9 fort winter 20/21/0
TH9 SkillerBee 10/7/0
TH9 Tatt Low 21/20/0
Will be great if we can display our enemy breakdown as well 😃

**Comment by xDp64xG** [comment]
What is the use of showing the heroes for war? There is no use for it, aside for looks, in my opinion, mainly for Super Elites

**Comment by iAmCLY** [comment]
The heroes is very important to assign the target.
